// Mocks generated by Mockito 5.4.6 from annotations
// in imagix/test/domain/profile/profile_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:imagix/core/network/result_state.dart' as _i4;
import 'package:imagix/domain/auth/repository/auth_repository.dart' as _i9;
import 'package:imagix/domain/common/model/user_profile.dart' as _i7;
import 'package:imagix/domain/profile/model/profile.dart' as _i5;
import 'package:imagix/domain/profile/model/profile_request.dart' as _i8;
import 'package:imagix/domain/profile/repository/profile_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i2.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ResultState<List<_i5.Profile>>> getProfilesByQuery(
    String? query, {
    required int? offset,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getProfilesByQuery,
              [query],
              {#offset: offset, #limit: limit},
            ),
            returnValue: _i3.Future<_i4.ResultState<List<_i5.Profile>>>.value(
              _i6.dummyValue<_i4.ResultState<List<_i5.Profile>>>(
                this,
                Invocation.method(
                  #getProfilesByQuery,
                  [query],
                  {#offset: offset, #limit: limit},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<List<_i5.Profile>>>);

  @override
  _i3.Future<_i4.ResultState<_i5.Profile>> getProfile(
    String? currentAuthId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, [currentAuthId, userId]),
            returnValue: _i3.Future<_i4.ResultState<_i5.Profile>>.value(
              _i6.dummyValue<_i4.ResultState<_i5.Profile>>(
                this,
                Invocation.method(#getProfile, [currentAuthId, userId]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<_i5.Profile>>);

  @override
  _i3.Future<_i4.ResultState<_i7.UserProfile>> updateProfile(
    String? userId,
    _i8.ProfileRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [userId, request]),
            returnValue: _i3.Future<_i4.ResultState<_i7.UserProfile>>.value(
              _i6.dummyValue<_i4.ResultState<_i7.UserProfile>>(
                this,
                Invocation.method(#updateProfile, [userId, request]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<_i7.UserProfile>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i9.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ResultState<_i7.UserProfile>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i3.Future<_i4.ResultState<_i7.UserProfile>>.value(
              _i6.dummyValue<_i4.ResultState<_i7.UserProfile>>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<_i7.UserProfile>>);

  @override
  _i3.Future<_i4.ResultState<bool>> register(
    String? email,
    String? password,
    String? username,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password, username]),
            returnValue: _i3.Future<_i4.ResultState<bool>>.value(
              _i6.dummyValue<_i4.ResultState<bool>>(
                this,
                Invocation.method(#register, [email, password, username]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<bool>>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.ResultState<bool>> deleteAccount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [userId]),
            returnValue: _i3.Future<_i4.ResultState<bool>>.value(
              _i6.dummyValue<_i4.ResultState<bool>>(
                this,
                Invocation.method(#deleteAccount, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<bool>>);

  @override
  _i3.Future<_i4.ResultState<bool>> restoreAccount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreAccount, [userId]),
            returnValue: _i3.Future<_i4.ResultState<bool>>.value(
              _i6.dummyValue<_i4.ResultState<bool>>(
                this,
                Invocation.method(#restoreAccount, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<bool>>);

  @override
  _i3.Future<_i4.ResultState<bool>> resendVerificationEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendVerificationEmail, [email]),
            returnValue: _i3.Future<_i4.ResultState<bool>>.value(
              _i6.dummyValue<_i4.ResultState<bool>>(
                this,
                Invocation.method(#resendVerificationEmail, [email]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<bool>>);

  @override
  _i3.Future<void> saveLocalUser(_i7.UserProfile? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveLocalUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearLocalUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearLocalUser, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
