// Mocks generated by Mockito 5.4.6 from annotations
// in imagix/test/domain/follow/follow_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:imagix/core/network/result_state.dart' as _i4;
import 'package:imagix/domain/auth/repository/auth_repository.dart' as _i7;
import 'package:imagix/domain/common/model/user_profile.dart' as _i8;
import 'package:imagix/domain/follow/model/follow.dart' as _i5;
import 'package:imagix/domain/follow/repository/follow_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FollowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFollowRepository extends _i1.Mock implements _i2.FollowRepository {
  MockFollowRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ResultState<List<_i5.Follow>>> getFollowing(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowing, [userId]),
            returnValue: _i3.Future<_i4.ResultState<List<_i5.Follow>>>.value(
              _i6.dummyValue<_i4.ResultState<List<_i5.Follow>>>(
                this,
                Invocation.method(#getFollowing, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<List<_i5.Follow>>>);

  @override
  _i3.Future<_i4.ResultState<List<_i5.Follow>>> getFollowers(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowers, [userId]),
            returnValue: _i3.Future<_i4.ResultState<List<_i5.Follow>>>.value(
              _i6.dummyValue<_i4.ResultState<List<_i5.Follow>>>(
                this,
                Invocation.method(#getFollowers, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<List<_i5.Follow>>>);

  @override
  _i3.Future<_i4.ResultState<bool>> toggleFollow(
    String? currentUserId,
    String? followingId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFollow, [currentUserId, followingId]),
            returnValue: _i3.Future<_i4.ResultState<bool>>.value(
              _i6.dummyValue<_i4.ResultState<bool>>(
                this,
                Invocation.method(#toggleFollow, [currentUserId, followingId]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<bool>>);

  @override
  _i3.Future<_i4.ResultState<bool>> removeFollower(
    String? currentUserId,
    String? followerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeFollower, [currentUserId, followerId]),
            returnValue: _i3.Future<_i4.ResultState<bool>>.value(
              _i6.dummyValue<_i4.ResultState<bool>>(
                this,
                Invocation.method(#removeFollower, [currentUserId, followerId]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<bool>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i7.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ResultState<_i8.UserProfile>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i3.Future<_i4.ResultState<_i8.UserProfile>>.value(
              _i6.dummyValue<_i4.ResultState<_i8.UserProfile>>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<_i8.UserProfile>>);

  @override
  _i3.Future<_i4.ResultState<bool>> register(
    String? email,
    String? password,
    String? username,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password, username]),
            returnValue: _i3.Future<_i4.ResultState<bool>>.value(
              _i6.dummyValue<_i4.ResultState<bool>>(
                this,
                Invocation.method(#register, [email, password, username]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<bool>>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.ResultState<bool>> deleteAccount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [userId]),
            returnValue: _i3.Future<_i4.ResultState<bool>>.value(
              _i6.dummyValue<_i4.ResultState<bool>>(
                this,
                Invocation.method(#deleteAccount, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<bool>>);

  @override
  _i3.Future<_i4.ResultState<bool>> restoreAccount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreAccount, [userId]),
            returnValue: _i3.Future<_i4.ResultState<bool>>.value(
              _i6.dummyValue<_i4.ResultState<bool>>(
                this,
                Invocation.method(#restoreAccount, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<bool>>);

  @override
  _i3.Future<_i4.ResultState<bool>> resendVerificationEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendVerificationEmail, [email]),
            returnValue: _i3.Future<_i4.ResultState<bool>>.value(
              _i6.dummyValue<_i4.ResultState<bool>>(
                this,
                Invocation.method(#resendVerificationEmail, [email]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<bool>>);

  @override
  _i3.Future<void> saveLocalUser(_i8.UserProfile? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveLocalUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearLocalUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearLocalUser, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
