// Mocks generated by Mockito 5.4.6 from annotations
// in imagix/test/domain/post/post_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:imagix/core/network/result_state.dart' as _i4;
import 'package:imagix/domain/auth/repository/auth_repository.dart' as _i8;
import 'package:imagix/domain/common/model/user_profile.dart' as _i9;
import 'package:imagix/domain/post/model/post.dart' as _i5;
import 'package:imagix/domain/post/model/post_request.dart' as _i7;
import 'package:imagix/domain/post/repository/post_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i2.PostRepository {
  MockPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ResultState<List<_i5.Post>>> getPosts({
    required int? offset,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, [], {#offset: offset, #limit: limit}),
            returnValue: _i3.Future<_i4.ResultState<List<_i5.Post>>>.value(
              _i6.dummyValue<_i4.ResultState<List<_i5.Post>>>(
                this,
                Invocation.method(#getPosts, [], {
                  #offset: offset,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<List<_i5.Post>>>);

  @override
  _i3.Future<_i4.ResultState<_i5.Post>> getPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [postId]),
            returnValue: _i3.Future<_i4.ResultState<_i5.Post>>.value(
              _i6.dummyValue<_i4.ResultState<_i5.Post>>(
                this,
                Invocation.method(#getPost, [postId]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<_i5.Post>>);

  @override
  _i3.Future<_i4.ResultState<List<_i5.Post>>> getLikedPosts({
    required int? offset,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLikedPosts, [], {
              #offset: offset,
              #limit: limit,
            }),
            returnValue: _i3.Future<_i4.ResultState<List<_i5.Post>>>.value(
              _i6.dummyValue<_i4.ResultState<List<_i5.Post>>>(
                this,
                Invocation.method(#getLikedPosts, [], {
                  #offset: offset,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<List<_i5.Post>>>);

  @override
  _i3.Future<_i4.ResultState<List<_i5.Post>>> getPostsByQuery(
    String? query, {
    required int? offset,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPostsByQuery,
              [query],
              {#offset: offset, #limit: limit},
            ),
            returnValue: _i3.Future<_i4.ResultState<List<_i5.Post>>>.value(
              _i6.dummyValue<_i4.ResultState<List<_i5.Post>>>(
                this,
                Invocation.method(
                  #getPostsByQuery,
                  [query],
                  {#offset: offset, #limit: limit},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<List<_i5.Post>>>);

  @override
  _i3.Future<_i4.ResultState<List<_i5.Post>>> getUserPosts(
    String? userId, {
    required int? offset,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUserPosts,
              [userId],
              {#offset: offset, #limit: limit},
            ),
            returnValue: _i3.Future<_i4.ResultState<List<_i5.Post>>>.value(
              _i6.dummyValue<_i4.ResultState<List<_i5.Post>>>(
                this,
                Invocation.method(
                  #getUserPosts,
                  [userId],
                  {#offset: offset, #limit: limit},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<List<_i5.Post>>>);

  @override
  _i3.Future<_i4.ResultState<_i5.Post>> create(
    String? userId,
    _i7.PostRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [userId, request]),
            returnValue: _i3.Future<_i4.ResultState<_i5.Post>>.value(
              _i6.dummyValue<_i4.ResultState<_i5.Post>>(
                this,
                Invocation.method(#create, [userId, request]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<_i5.Post>>);

  @override
  _i3.Future<_i4.ResultState<bool>> update(
    String? userId,
    String? postId,
    _i7.PostRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [userId, postId, request]),
            returnValue: _i3.Future<_i4.ResultState<bool>>.value(
              _i6.dummyValue<_i4.ResultState<bool>>(
                this,
                Invocation.method(#update, [userId, postId, request]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<bool>>);

  @override
  _i3.Future<_i4.ResultState<bool>> delete(String? userId, String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [userId, postId]),
            returnValue: _i3.Future<_i4.ResultState<bool>>.value(
              _i6.dummyValue<_i4.ResultState<bool>>(
                this,
                Invocation.method(#delete, [userId, postId]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<bool>>);

  @override
  _i3.Future<_i4.ResultState<bool>> toggleLike(
    String? userId,
    String? postId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleLike, [userId, postId]),
            returnValue: _i3.Future<_i4.ResultState<bool>>.value(
              _i6.dummyValue<_i4.ResultState<bool>>(
                this,
                Invocation.method(#toggleLike, [userId, postId]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<bool>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i8.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ResultState<_i9.UserProfile>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i3.Future<_i4.ResultState<_i9.UserProfile>>.value(
              _i6.dummyValue<_i4.ResultState<_i9.UserProfile>>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<_i9.UserProfile>>);

  @override
  _i3.Future<_i4.ResultState<bool>> register(
    String? email,
    String? password,
    String? username,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password, username]),
            returnValue: _i3.Future<_i4.ResultState<bool>>.value(
              _i6.dummyValue<_i4.ResultState<bool>>(
                this,
                Invocation.method(#register, [email, password, username]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<bool>>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.ResultState<bool>> deleteAccount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [userId]),
            returnValue: _i3.Future<_i4.ResultState<bool>>.value(
              _i6.dummyValue<_i4.ResultState<bool>>(
                this,
                Invocation.method(#deleteAccount, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<bool>>);

  @override
  _i3.Future<_i4.ResultState<bool>> restoreAccount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreAccount, [userId]),
            returnValue: _i3.Future<_i4.ResultState<bool>>.value(
              _i6.dummyValue<_i4.ResultState<bool>>(
                this,
                Invocation.method(#restoreAccount, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<bool>>);

  @override
  _i3.Future<_i4.ResultState<bool>> resendVerificationEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendVerificationEmail, [email]),
            returnValue: _i3.Future<_i4.ResultState<bool>>.value(
              _i6.dummyValue<_i4.ResultState<bool>>(
                this,
                Invocation.method(#resendVerificationEmail, [email]),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<bool>>);

  @override
  _i3.Future<void> saveLocalUser(_i9.UserProfile? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveLocalUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearLocalUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearLocalUser, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
